services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
    entrypoint:
      - /surreal
      - start
      - --auth
      - --user
      - root
      - --pass
      - password
    volumes:
      - ./volumes/surrealdb:/mydata
